WITH
    OfflineSalesAmount as (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as SALES_AMOUNT
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
    )
    
SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) as SALES
FROM PRODUCT as a
    JOIN OfflineSalesAmount as b ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY SALES DESC, a.PRODUCT_CODE ASC